{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsautoscalingplans\/concurrentupdateexception\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/ConcurrentUpdateException\/message","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"message","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:19AWSAutoScalingPlans25ConcurrentUpdateExceptionV7messageSSSgvp","modules":[{"name":"AWSAutoScalingPlans"}]},"hierarchy":{"paths":[["doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans","doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/ConcurrentUpdateException"]]},"references":{"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans":{"role":"collection","title":"AWSAutoScalingPlans","abstract":[],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans","kind":"symbol","type":"topic","url":"\/documentation\/awsautoscalingplans"},"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans/ConcurrentUpdateException":{"role":"symbol","title":"ConcurrentUpdateException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConcurrentUpdateException"}],"abstract":[{"type":"text","text":"Concurrent updates caused an exception, for example, if you request an update to a scaling plan that already has a pending update."}],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/ConcurrentUpdateException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConcurrentUpdateException"}],"url":"\/documentation\/awsautoscalingplans\/concurrentupdateexception"},"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans/ConcurrentUpdateException/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/ConcurrentUpdateException\/message","kind":"symbol","type":"topic","url":"\/documentation\/awsautoscalingplans\/concurrentupdateexception\/message"}}}