{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight\/InternalFailureException","preciseIdentifier":"s:13AWSQuickSight24InternalFailureExceptionV","text":"InternalFailureException"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsquicksight\/creategroupoutputerror\/internalfailureexception(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight\/CreateGroupOutputError\/internalFailureException(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalFailureException","preciseIdentifier":"s:13AWSQuickSight24InternalFailureExceptionV"},{"kind":"text","text":")"}],"title":"CreateGroupOutputError.internalFailureException(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:13AWSQuickSight22CreateGroupOutputErrorO24internalFailureExceptionyAcA08InternalhI0VcACmF","modules":[{"name":"AWSQuickSight"}]},"hierarchy":{"paths":[["doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight","doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight\/CreateGroupOutputError"]]},"references":{"doc://AWSQuickSight/documentation/AWSQuickSight/InternalFailureException":{"role":"symbol","title":"InternalFailureException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalFailureException"}],"abstract":[{"type":"text","text":"An internal failure occurred."}],"identifier":"doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight\/InternalFailureException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalFailureException"}],"url":"\/documentation\/awsquicksight\/internalfailureexception"},"doc://AWSQuickSight/documentation/AWSQuickSight/CreateGroupOutputError/internalFailureException(_:)":{"role":"symbol","title":"CreateGroupOutputError.internalFailureException(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalFailureException","preciseIdentifier":"s:13AWSQuickSight24InternalFailureExceptionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight\/CreateGroupOutputError\/internalFailureException(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsquicksight\/creategroupoutputerror\/internalfailureexception(_:)"},"doc://AWSQuickSight/documentation/AWSQuickSight/CreateGroupOutputError":{"role":"symbol","title":"CreateGroupOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateGroupOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight\/CreateGroupOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateGroupOutputError"}],"url":"\/documentation\/awsquicksight\/creategroupoutputerror"},"doc://AWSQuickSight/documentation/AWSQuickSight":{"role":"collection","title":"AWSQuickSight","abstract":[],"identifier":"doc:\/\/AWSQuickSight\/documentation\/AWSQuickSight","kind":"symbol","type":"topic","url":"\/documentation\/awsquicksight"}}}