{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException","preciseIdentifier":"s:10AWSAppSync24InternalFailureExceptionV","text":"InternalFailureException"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappsync\/getintrospectionschemaoutputerror\/internalfailureexception(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/GetIntrospectionSchemaOutputError\/internalFailureException(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalFailureException","preciseIdentifier":"s:10AWSAppSync24InternalFailureExceptionV"},{"kind":"text","text":")"}],"title":"GetIntrospectionSchemaOutputError.internalFailureException(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10AWSAppSync33GetIntrospectionSchemaOutputErrorO24internalFailureExceptionyAcA08InternaliJ0VcACmF","modules":[{"name":"AWSAppSync"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppSync\/documentation\/AWSAppSync","doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/GetIntrospectionSchemaOutputError"]]},"references":{"doc://AWSAppSync/documentation/AWSAppSync/GetIntrospectionSchemaOutputError/internalFailureException(_:)":{"role":"symbol","title":"GetIntrospectionSchemaOutputError.internalFailureException(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailureException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalFailureException","preciseIdentifier":"s:10AWSAppSync24InternalFailureExceptionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/GetIntrospectionSchemaOutputError\/internalFailureException(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync\/getintrospectionschemaoutputerror\/internalfailureexception(_:)"},"doc://AWSAppSync/documentation/AWSAppSync/GetIntrospectionSchemaOutputError":{"role":"symbol","title":"GetIntrospectionSchemaOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetIntrospectionSchemaOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/GetIntrospectionSchemaOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetIntrospectionSchemaOutputError"}],"url":"\/documentation\/awsappsync\/getintrospectionschemaoutputerror"},"doc://AWSAppSync/documentation/AWSAppSync":{"role":"collection","title":"AWSAppSync","abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync"},"doc://AWSAppSync/documentation/AWSAppSync/InternalFailureException":{"role":"symbol","title":"InternalFailureException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalFailureException"}],"abstract":[{"type":"text","text":"An internal AppSync error occurred. Try your request again."}],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/InternalFailureException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalFailureException"}],"url":"\/documentation\/awsappsync\/internalfailureexception"}}}