{"variants":[{"paths":["\/documentation\/awsappflow\/internalserverexception\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"AWSAppflow"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/AWSAppflow\/documentation\/AWSAppflow","doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException"]]},"references":{"doc://AWSAppflow/documentation/AWSAppflow":{"role":"collection","title":"AWSAppflow","abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow","kind":"symbol","type":"topic","url":"\/documentation\/awsappflow"},"doc://AWSAppflow/documentation/AWSAppflow/InternalServerException/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappflow\/internalserverexception\/!=(_:_:)"},"doc://AWSAppflow/documentation/AWSAppflow/InternalServerException":{"role":"symbol","title":"InternalServerException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServerException"}],"abstract":[{"type":"text","text":"An internal service error occurred during the processing of your request. Try again later."}],"identifier":"doc:\/\/AWSAppflow\/documentation\/AWSAppflow\/InternalServerException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServerException"}],"url":"\/documentation\/awsappflow\/internalserverexception"}}}