{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsauditmanager\/internalserverexception\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/InternalServerException\/message","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This member is required."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"message","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:15AWSAuditManager23InternalServerExceptionV7messageSSSgvp","modules":[{"name":"AWSAuditManager"}]},"hierarchy":{"paths":[["doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager","doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/InternalServerException"]]},"references":{"doc://AWSAuditManager/documentation/AWSAuditManager":{"role":"collection","title":"AWSAuditManager","abstract":[],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager","kind":"symbol","type":"topic","url":"\/documentation\/awsauditmanager"},"doc://AWSAuditManager/documentation/AWSAuditManager/InternalServerException/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This member is required."}],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/InternalServerException\/message","kind":"symbol","type":"topic","url":"\/documentation\/awsauditmanager\/internalserverexception\/message"},"doc://AWSAuditManager/documentation/AWSAuditManager/InternalServerException":{"role":"symbol","title":"InternalServerException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServerException"}],"abstract":[{"type":"text","text":"An internal service error occurred during the processing of your request. Try again later."}],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/InternalServerException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServerException"}],"url":"\/documentation\/awsauditmanager\/internalserverexception"}}}